name: Get-Sound-Samples
on:
  workflow_dispatch:
    inputs:
      search_query:
        description: "Search Query in format 'term'+'term'..."
        required: true
        default: "loop"

jobs:
  collecting-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: yarn version
      - run: node -v
      - run: |
          echo "Env: ${{ github.event.inputs.search_query }}"
